/**
 * @file vulkan_scene_mesh.h
 * @brief Per-asset mesh (vertex + index buffers + submeshes) for the deferred
 *        scene pipeline (Phase 5 Week 1).
 *
 * Lives in `gws::renderer::gpu::` alongside `Texture` and `Material`.
 * Distinct from the older `vks::VulkanMesh` (which uses a different vertex
 * layout and a different namespace) — kept separate so we don't disturb
 * Phase 3 callers that still reference the old class.
 */

#pragma once

#include "culling.h" // for AABB (used by-value as a member)
#include <vulkan/vulkan.h>
#include <glm/glm.hpp>
#include <cstdint>
#include <memory>
#include <vector>

namespace gws::renderer::gpu {

class VulkanDevice;

/// Standard PBR vertex. Position/normal/UV0/tangent — matches what the
/// glTF loader produces and what the textured G-Buffer pipeline consumes.
struct SceneVertex {
    glm::vec3 position;
    glm::vec3 normal;
    glm::vec2 uv;
    glm::vec4 tangent; // .xyz = tangent vec, .w = handedness (+1/-1)
};

/// One LOD tier of a submesh — its own contiguous range in the mesh's
/// shared index buffer. LOD 0 is the source resolution; subsequent LODs
/// are progressively decimated copies generated by meshoptimizer.
struct MeshLod {
    uint32_t index_offset = 0;
    uint32_t index_count  = 0;
    /// Distance (in world units) at which this LOD is preferred over
    /// the previous one. LOD 0 has threshold 0.0 (always preferred at
    /// close range); LOD i is selected when `camera_distance >= threshold[i]`.
    float    distance_threshold = 0.0f;
};

/// One meshlet — a small cluster of triangles (typically 64–124) with its
/// own local-space bounding sphere. Used for per-cluster culling: at draw
/// time the renderer transforms each meshlet's sphere to world space, tests
/// it against the camera frustum, and skips the meshlet's `vkCmdDrawIndexed`
/// when it falls outside.
///
/// `first_index` / `index_count` index into the parent mesh's index buffer.
/// During `Mesh::create` LOD 0's triangles are reordered into meshlet order,
/// so a meshlet's draw range is a contiguous sub-range of the LOD 0 indices.
struct Meshlet {
    uint32_t first_index = 0;
    uint32_t index_count = 0;
    /// Bounding sphere in mesh-local space (no model transform applied).
    glm::vec3 center{0.0f};
    float     radius = 0.0f;
};

/// One drawable section of a mesh, sharing a single material.
/// `lods` always contains at least one entry (LOD 0 = full resolution).
struct Submesh {
    uint32_t material_index = 0;       // index into the parent Scene::materials
    std::vector<MeshLod> lods;         // [0] = full res; subsequent = decimated
    /// Meshlets covering LOD 0. Empty for trivially small meshes (<= one
    /// meshlet's worth of triangles), in which case the renderer falls back
    /// to the per-submesh draw_submesh path.
    std::vector<Meshlet> lod0_meshlets;

    // Convenience: full-mesh range ⇔ lods[0].
    uint32_t index_offset() const { return lods.empty() ? 0u : lods[0].index_offset; }
    uint32_t index_count()  const { return lods.empty() ? 0u : lods[0].index_count;  }
};

/// Batches the staging uploads of many meshes into ONE submit.
///
/// WHY THIS EXISTS. Mesh geometry now lives in DEVICE_LOCAL memory, which can
/// only be written through a staging copy on the queue. The obvious shape —
/// one command buffer, submit, `vkQueueWaitIdle`, per mesh — is what the
/// texture path does, and it is fine for one texture. A terrain rebuild creates
/// up to 256 chunk meshes in a burst; stalling the queue 256 times would trade
/// the bandwidth problem for a worse latency one.
///
/// So a batch accumulates every mesh's bytes into ONE host staging buffer,
/// records one `vkCmdCopyBuffer` per destination, and submits once. That also
/// keeps the allocation count down: one staging allocation per batch rather
/// than one per mesh.
///
/// Not thread-safe, and deliberately scope-shaped: build meshes, let the batch
/// go out of scope, and the flush happens in the destructor.
class MeshUploadBatch {
public:
    explicit MeshUploadBatch(VulkanDevice* device) : device_(device) {}
    ~MeshUploadBatch();

    MeshUploadBatch(const MeshUploadBatch&)            = delete;
    MeshUploadBatch& operator=(const MeshUploadBatch&) = delete;

    /// Queue `size` bytes from `src` to be copied into `dst` at flush time.
    /// The bytes are copied into the batch immediately, so `src` need not
    /// outlive this call.
    void stage(VkBuffer dst, const void* src, VkDeviceSize size);

    /// Upload everything queued and wait for it. Returns false if the staging
    /// buffer could not be created — callers should treat the meshes built
    /// through this batch as failed. Safe to call more than once; a flush with
    /// nothing queued is a no-op.
    bool flush();

    /// How many copies are waiting. Used by tests and diagnostics.
    size_t pending() const { return copies_.size(); }

private:
    struct Copy {
        VkBuffer     dst    = VK_NULL_HANDLE;
        VkDeviceSize offset = 0;   // into the staging blob
        VkDeviceSize size   = 0;
    };
    VulkanDevice*        device_ = nullptr;
    std::vector<uint8_t> blob_;    // CPU-side staging contents
    std::vector<Copy>    copies_;
};

class Mesh {
public:
    Mesh() = default;
    ~Mesh();

    Mesh(const Mesh&) = delete;
    Mesh& operator=(const Mesh&) = delete;
    Mesh(Mesh&&) noexcept;
    Mesh& operator=(Mesh&&) noexcept;

    /// Build a GPU-resident mesh. Indices are uint32. The submeshes vector
    /// describes how to split the index buffer into material-homogeneous
    /// chunks; pass a single submesh covering all indices for simple meshes.
    /// Each submesh's `lods` vector should already be populated — typically
    /// by `Mesh::generate_lods` before calling.
    /// `extra_vbo_usage` adds usage bits to the vertex buffer — e.g.
    /// VK_BUFFER_USAGE_STORAGE_BUFFER_BIT so a compute skinning pass can write
    /// vertices into it (the SkinnedMesh output path). 0 = plain vertex buffer.
    ///
    /// `batch` lets a caller building MANY meshes at once pay for one submit
    /// instead of one per mesh. Pass null and the mesh uploads and waits
    /// immediately, which is what a one-off caller wants. A terrain rebuild
    /// creates hundreds of meshes in a burst and must not stall the queue
    /// hundreds of times — see MeshUploadBatch.
    ///
    /// A mesh built through a batch is NOT usable until that batch is flushed:
    /// its buffers exist but hold nothing. The batch flushes in its destructor,
    /// so the common scoped use is safe by construction.
    static std::unique_ptr<Mesh> create(VulkanDevice* device,
                                        const std::vector<SceneVertex>& vertices,
                                        const std::vector<uint32_t>& indices,
                                        std::vector<Submesh> submeshes,
                                        VkBufferUsageFlags extra_vbo_usage = 0,
                                        class MeshUploadBatch* batch = nullptr);

    /// Bind vertex+index buffers on the supplied command buffer.
    void bind(VkCommandBuffer cmd) const;

    /// Issue `vkCmdDrawIndexed` for one submesh's LOD tier. `lod_index`
    /// is clamped to the available LODs.
    void draw_submesh(VkCommandBuffer cmd, size_t submesh_idx,
                      size_t lod_index = 0) const;

    /// Issue `vkCmdDrawIndexed` for a single meshlet (a sub-range of the
    /// shared index buffer). Caller must have already done frustum
    /// culling — this is just the draw call wrapper.
    void draw_meshlet(VkCommandBuffer cmd, uint32_t first_index,
                      uint32_t index_count) const;

    /// Pick the highest-detail LOD tier for the given world-space distance.
    /// Returns 0 (LOD 0) if `submesh_idx` is out of range or the submesh
    /// has only LOD 0. Comparison: returns the largest `i` such that
    /// `lods[i].distance_threshold <= distance`.
    size_t select_lod(size_t submesh_idx, float camera_distance) const;

    /// Take a single-LOD submesh layout (one full-res range per submesh)
    /// and append meshoptimizer-decimated tiers. The supplied index buffer
    /// is mutated in place — extra ranges are appended to its tail and
    /// `submeshes[i].lods` is populated.
    ///
    /// `lod_ratios`: each entry is the target index-count ratio relative to
    /// the source (e.g. 0.5 = 50%, 0.25 = 25%). One LOD tier per ratio is
    /// generated and assigned a `distance_threshold` from `lod_distances`
    /// (which must be the same length).
    static void generate_lods(const std::vector<SceneVertex>& vertices,
                              std::vector<uint32_t>& indices,
                              std::vector<Submesh>& submeshes,
                              const std::vector<float>& lod_ratios,
                              const std::vector<float>& lod_distances);

    const std::vector<Submesh>& submeshes() const { return submeshes_; }
    uint32_t vertex_count() const { return vertex_count_; }
    uint32_t index_count() const  { return index_count_; }

    /// Raw GPU buffer handles — needed by VulkanRtScene to build a BLAS
    /// from this mesh's geometry without copying. The buffers carry the
    /// AS-build usage bits when the device supports ray tracing.
    VkBuffer get_vertex_buffer() const { return vbo_; }
    VkBuffer get_index_buffer()  const { return ibo_; }
    /// Backing memory of the vertex buffer (host-visible). Exposed so a
    /// compute-skinning pass / test can map + read the (possibly compute-
    /// written) vertices without a staging copy.
    VkDeviceMemory get_vertex_memory() const { return vbo_memory_; }

    /// Get the mesh's bounding box in local space (computed at load time).
    const AABB& bounding_box() const { return bounding_box_; }

    /// True when the mesh's triangle winding is not trustworthy and the
    /// G-Buffer renderer must draw it from both sides. OBJ assets set this
    /// to true (their authored winding is not standardised); glTF (spec
    /// mandates CCW) and the engine's primitive generators stay false.
    /// VulkanGBuffer's `draw_items` consults this per-draw to pick between
    /// the cull-back and cull-none pipelines.
    bool is_double_sided() const { return double_sided_; }
    void set_double_sided(bool d) { double_sided_ = d; }

    /// Vertex input descriptors compatible with this mesh's layout. Used by
    /// the geometry pipeline at creation time.
    static VkVertexInputBindingDescription vertex_binding();
    static std::vector<VkVertexInputAttributeDescription> vertex_attributes();

private:
    VulkanDevice*  device_      = nullptr;
    VkBuffer       vbo_         = VK_NULL_HANDLE;
    VkDeviceMemory vbo_memory_  = VK_NULL_HANDLE;
    VkBuffer       ibo_         = VK_NULL_HANDLE;
    VkDeviceMemory ibo_memory_  = VK_NULL_HANDLE;
    uint32_t       vertex_count_ = 0;
    uint32_t       index_count_  = 0;
    bool           double_sided_ = false;
    std::vector<Submesh> submeshes_;
    AABB           bounding_box_;

    void destroy();
};

} // namespace gws::renderer::gpu
